#ifndef GAMERULES_H_INCLUDE
#define GAMERULES_H_INCLUDE

#define PEBBLE_RED = 0xFF0000
#define PEBBLE_GREEN = 0x00FF00
#define PEBBLE_BLUE = 0x0000FF
#define PEBBLE_YELLOW = 0xFFFF00
#define PEBBLE_VIOLET = 0x7000FF
#define PEBBLE_ORANGE = 0xFF7F00
#define PEBBLE_PINK = 0xFF00FF
#define PEBBLE_TURQUOISE = 0x00FFFF

#define PLAYER_LIVES = 10
#define OS = "Windows"

#endif
